### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Dodeedoo** [SkyblockClient/Skyclient-Installer-Windows#2]
https://mmus.me/blog/certificates/
You can sign the executable for windows so it doesn't warn the user of an 'unknown developer'

**Comment by KTibow** [comment]
You need to install the certificate first, which is even worse.

**Comment by Wyvest** [comment]
The non-beta Windows installer is now signed. If the beta installer comes out of beta (which I don't think it ever will for unrelated reasons), we will also sign it
